argo-cd:
  server:
    insecure: true
    service:
      type: NodePort
      nodePortHttp: 30004
      nodePortHttps: null
    ingress:
      enabled: false
#      ingressClassName: "nginx"
#      hostname: argocd.18.220.254.204.nip.io
  dex:
    enabled: false
  notifications:
    enabled: false

  #affinity:
  #  nodeAffinity:
  #    matchExpressions:
  #      - key: topology.kubernetes.io/zone
  #        operator: In
  #        values: