argo-cd:
  server:
    insecure: true
    service:
      type: NodePort
      nodePortHttp: 30004
      nodePortHttps: null
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: argocd.172.17.90.93.nip.io
  dex:
    enabled: false
  notifications:
    enabled: false

  #affinity:
  #  nodeAffinity:
  #    matchExpressions:
  #      - key: topology.kubernetes.io/zone
  #        operator: In
  #        values:
