argo-cd:
  server:
    insecure: true
    service:
      type: NodePort
      nodePortHttp: 30004
      nodePortHttps: null
  dex:
    enabled: false
  notifications:
    enabled: false
  ingress:
    enabled: true

  #affinity:
  #  nodeAffinity:
  #    matchExpressions:
  #      - key: topology.kubernetes.io/zone
  #        operator: In
  #        values: