apiVersion: v2
name: longhorm
description: A Helm chart for Kubernetes
dependencies:
  - name: longhorn
    version: 1.11.0
    repository: https://charts.longhorn.io
type: application
version: 0.1.0
appVersion: "1.16.0"
